cvsite:
    path:     /
    defaults: { _controller: CvsiteBundle:Default:accueil }

telechargementCvPdf:
    pattern:  /telechargementCvPdf
    defaults: { _controller: CvsiteBundle:Default:telechargementCvPdf }
    