CvsiteBundle\Entity\Skill:
  type: entity
  table: skill
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
      
  manyToMany:
    image:
      targetEntity: Image
      joinTable:
        name: skill_image
        joinColumns:
          article_id:
            referencedColumnName: id
        inverseJoinColumns:
          image_id:
            referencedColumnName: id
  manyToOne:
    category:
      targetEntity: Category
      cascade:                  [ remove, persist ]
      joinColumn:
        name: category_id
        referencedColumnName: id
